version: '3'

services:
  nginx:
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/larabuild
      - ./docker/nginx/nginx.sh:/var/nginx.sh
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
  php:
    build: ./docker/php
    volumes:
      - .:/var/www/larabuild
      - ../fullCore:/var/www/fullCore
      - ~/.cache/composer:/.cache/composer
    working_dir: /var/www/larabuild
  npm:
    build: ./docker/npm
    volumes:
      - .:/var/www/larabuild
    working_dir: /var/www/larabuild
    command: "npm run hot"
